---
resources:
- name: my-resource
  type: git
  source:
    branch: master
    uri: https://github.com/rsridivya/helloworld.git
- name: my-docker-resource
  type: git
  source:
    branch: master
    uri: https://github.com/rsridivya/gannett_exercise.git    


jobs:
- name: Build_Web_App_Run_Tests
  plan:
  - get: my-resource
    trigger: true
  - task: build-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: centos
      run:
        path: sh
        args:
        - -exc
        - |
          yum install git wget -y 
          git clone https://github.com/rsridivya/helloworld.git
          wget https://dl.google.com/go/go1.9.2.linux-amd64.tar.gz
          tar xzf go*
          mv go /opt
          export PATH=$PATH:/opt
          cd helloworld/
          /opt/go/bin/go build hello.go
          /opt/go/bin/go test -cover
          
- name: web-app-gannett
  plan:
  - get: my-docker-resource
    trigger: true
  - task: run-web-app
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: amazonlinux}
      run:
        path: /bin/sh
        args:
        - -xec
        - |
          yum install docker -y
          service docker start
          curl -L https://raw.githubusercontent.com/aelsabbahy/goss/master/extras/dgoss/dgoss -o /usr/local/bin/dgoss
          chmod +rx /usr/local/bin/dgoss
          mkdir ~/Downloads
          curl -L https://github.com/aelsabbahy/goss/releases/download/v0.3.5/goss-linux-amd64 -o ~/Downloads/goss-linux-amd64
          export GOSS_PATH=~/Downloads/goss-linux-amd64
                    echo 'file:
            /opt/helloworld/hello:
              exists: true
              mode: "0755"
              size: 6140803
              owner: root
              group: root
              filetype: file
              contains: []
          process:
            hello:
              running: true
          http:
            http://127.0.0.1:8080:
              status: 200
              allow-insecure: false
              no-follow-redirects: false
              timeout: 5000
              body: []' > goss.yaml
          cat goss.yaml
          sh /usr/local/bin/dgoss run -p 8080:8080 "rsridivya/gannett_exercise" hello
